# Default values for helm-mernapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 5

appName: todo-app

serviceKind:
  frontend: frontend-service
  backend: backend-service

deploymentKind:
  frontend: frontend
  backend: backend

backend-image:
  repository: deanosaurx/backend
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.0.26

frontend-image:
  repository: deanosaurx/frontend
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.0.26
