appName: todo-app

serviceKind:
  frontend: frontend-service
  backend: backend-service

deploymentKind:
  frontend: frontend
  backend: backend

imageName:
  frontend: deanosaurx/frontend
  backend: deanosaurx/backend

imageTag:
  frontend: 1.0.26
  backend: 1.0.26
