helm:
  parameters:
    - name: image.name
      value: deanosaurx/backend
      forcestring: true
    - name: image.tag
      value: 1.0.26
      forcestring: true
    - name: image.name
      value: deanosaurx/frontend
      forcestring: true
    - name: image.tag
      value: 1.0.26
      forcestring: true
  appName: todo-app
  serviceKind:
    frontend: frontend-service
    backend: backend-service
  deploymentKind:
    frontend: frontend
    backend: backend
