apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontendalias=deanosaurx/frontend:~1, backendalias=deanosaurx/backend:~1
    argocd-image-updater.argoproj.io/frontendalias.helm.image-name: deanosaurx/frontend
    argocd-image-updater.argoproj.io/frontendalias.helm.image-tag: 1.0.50
    argocd-image-updater.argoproj.io/frontendalias.helm.image-name: deanosaurx/frontend
    argocd-image-updater.argoproj.io/frontendalias.helm.image-tag: 1.0.48
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: "https://github.com/deanosaurx/project-int.git"
    path: charts/helm-mernapp
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
