apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=deanosaurx/frontend, backend=deanosaurx/backend
    argocd-image-updater.argoproj.io/frontend.mern-app.frontend.containers.image: frontend
    argocd-image-updater.argoproj.io/frontend.mern-app.image.tag: mern-app.image.tag
    argocd-image-updater.argoproj.io/backend.mern-app.image.name: mern-app.image.name
    argocd-image-updater.argoproj.io/backend.mern-app.image.tag: mern-app.image.tag
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: "https://github.com/deanosaurx/project-int.git"
    path: charts/helm-mernapp
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
