apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.serviceKind.backend }}"
  namespace: "{{ .Values.appNamespace }}"
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: backend
  type: ClusterIP
