apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.backend.service.name }}"
spec:
  ports:
    - port: "{{ .Values.backend.service.ports.port }}"
      targetPort: "{{ .Values.backend.service.ports.targetPort }}"
  selector:
    app: "{{ .Values.backend.deploy.name }}"
  type: "{{ .Values.backend.service.type }}"
