apiVersion: v1
kind: Service
metadata:
  namespace: "{{.Values.appNamespace }}"
  name: "{{ .Values.serviceKind.frontend }}"
spec:
  ports:
    - port: 80
      targetPort: 3001
  selector:
    app: frontend
  type: ClusterIP
