apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: "{{ .Values.appNamespace }}"
  labels:
    app: "{{ .Values.deploymentKind.backend }}"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "{{ .Values.deploymentKind.backend }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.deploymentKind.backend }}"
    spec:
      containers:
        - name: "{{ .Values.deploymentKind.backend }}"
          image: deanosaurx/backend:v1.0.1
          ports:
            - containerPort: 8000
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
