apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: "{{ .Values.deploymentKind.backend }}"
spec:
  replicas: "{{ .Values.replicaCount }}"
  selector:
    matchLabels:
      app: "{{ .Values.deploymentKind.backend }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.deploymentKind.backend }}"
    spec:
      containers:
        - name: "{{ .Values.deploymentKind.backend }}"
          image: "{{ .Values.backend-image.repository }}:{{ .Values.backend-image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
