apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .helm.deploymentKind.frontend }}"
  labels:
    app: "{{ .helm.deploymentKind.frontend }}"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: "{{ .helm.deploymentKind.frontend }}"
  template:
    metadata:
      labels:
        app: "{{ .helm.deploymentKind.frontend }}"
    spec:
      containers:
        - name: "{{ .helm.deploymentKind.frontend }}"
          image: "{{ .helm.parameters[2].value }}:{{ .helm.parameters[3].value }}"
          ports:
            - containerPort: 3001
