apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.deploymentKind.frontend }}"
  labels:
    app: "{{ .Values.deploymentKind.frontend }}"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: "{{ .Values.deploymentKind.frontend }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.deploymentKind.frontend }}"
    spec:
      containers:
        - name: "{{ .Values.deploymentKind.frontend }}"
          image: "{{ .Values.imageName.frontend }}:{{ .Values.imageTag.frontend }}"
          ports:
            - containerPort: 3001
