apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.deploymentKind.frontend }}"
  namespace: "{{ .Values.appNamespace}}"
  labels:
    app: "{{ .Values.deploymentKind.frontend }}"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "{{ .Values.deploymentKind.frontend }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.deploymentKind.frontend }}"
    spec:
      containers:
        - name: "{{ .Values.deploymentKind.frontend }}"
          image: deanosaurx/frontend:v1.0.8
          ports:
            - containerPort: 3001
