apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: todo-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/deanosaurx
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/deploy/charts/mernapp
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: todo-app
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./deploy/charts/mernapp
  prune: true
  sourceRef:
    kind: GitRepository
    name: todo-app
  targetNamespace: todo-app
